# To get started with security, check out the documentation:
# https://symfony.com/doc/currentDMIN }/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                darren:
                  password: $2y$12$lnA47mh47.DX/VJVpnVkLuKznZyuqORDnjOdZenbygIdBpsB//u3i
                  roles: 'ROLE_USER'
                admin:
                  password: $2y$12$lnA47mh47.DX/VJVpnVkLuKznZyuqORDnjOdZenbygIdBpsB//u3i
                  roles: 'ROLE_ADMIN'

    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt
        cost: 12
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            form_login:
              login_path: login
              check_path: login
              succes_handler: app.login_handler
            logout:
              path: /logout
              target: /
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
      - {path: ^/admin, roles: ROLE_ADMIN}
      - {path: ^/gebruiker, roles: ROLE_USER}